name: Generate metrics + contribution assests
on:
  schedule: # execute every 168 hours (1 week)
    - cron: "0 0 * * 0" # Run every Sunday at midnight (0:00)
  workflow_dispatch:
  
#   # run on every push on the master branch
#   push:
#     branches:
#     - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: assets/github-contribution-grid-snake2.svg
          snake_color: 'green'
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: avivajpeyi
          template: classic
          base: activity, repositories, metadata
          base_indepth: yes
          config_octicon: yes
          config_timezone: Australia/Melbourne
          plugin_lines: yes
          plugin_lines_history_limit: 8
          plugin_lines_repositories_limit: 40
          plugin_lines_sections: base
          plugin_habits_languages_threshold: 0%
          config_display: columns
      
      
#       - name: move assets 
#         run: mv *.svg assets/ 
        
#       - name: Remove File
#         uses: JesseTG/rm@v1.0.3
#         with:
#           path: github-metrics.svg
        
#       - uses: GuillaumeFalourd/git-commit-push@v1.3
#         with:
#           commit_message: "update assets"
#           force: true
#         env:
#           GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          
